# Generated by Django 5.1 on 2024-08-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interestsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessages',
        ),
    ]
