# Generated by Django 5.1 on 2024-08-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interestsapp', '0003_chatmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='interest_id',
        ),
    ]
